defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: <%= ENV['POSTGRES_USERNAME'] || ENV['USER'] %>

development:
  database: piggybank_dev
  host: localhost
  <<: *defaults

test:
  database: piggybank_test
  host: localhost
  min_messages: WARNING
  <<: *defaults

production:
  database: piggybank_prod
  <<: *defaults

